### ISSUE TITLE
Flags should be "u" by default

### ISSUE THREAD

**Issue by Aloso** [Kyza/unplugin-pomsky#1]
Pomsky should be Unicode aware by default, so calling `make()` should use the "u" flag. If someone wants to disable Unicode support, they can pass an empty string.

An alternative is to always pass "u" in addition to the user-provided flags:

```js
new RegExp(regex, `u${flags}`)
```

But then it's impossible to opt out of Unicode support. Another option is to accept an object:

```js
make({ ignoreCase: true, unicode: false })
```

**Comment by Kyza** [comment]
I couldn't think of a clean way of representing the unicode flag as disabled in the string format, so I made it always enabled there and added the object option you suggested as well.

https://github.com/pomsky-lang/unplugin-pomsky#unicode-aware
